VAGRANT_API_VERSION = '2'

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'playbook.yml'
    ansible.verbose = true
  end
end
